apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    {{- if $.Values.global.acmCertificateArn }}
    alb.ingress.kubernetes.io/certificate-arn: {{ $.Values.global.acmCertificateArn }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    {{- end }}
spec:
  ingressClassName: alb
  rules:
    - host: api.{{ $.Values.global.domain }}
      http:
        paths:
          - path: /api/products
            pathType: Prefix
            backend:
              service:
                name: product-service
                port:
                  number: {{ index $.Values.services "product-service" "port" | default 3000 }}
          - path: /api/users
            pathType: Prefix
            backend:
              service:
                name: user-service
                port:
                  number: {{ index $.Values.services "user-service" "port" | default 3001 }}
          - path: /api/orders
            pathType: Prefix
            backend:
              service:
                name: order-service
                port:
                  number: {{ index $.Values.services "order-service" "port" | default 3002 }}
