{{- range $name, $svc := .Values.services }}
{{- if and $svc.enabled $svc.db }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $name }}-db-pvc
spec:
  storageClassName: ebs-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $svc.db.storage }}
---
{{- end }}
{{- end }}
