# Default values for cloudmart.

global:
  domain: cloudmart.example.com
  dbPassword: defaultpassword

services:
  frontend:
    enabled: true
    image:
      repository: 500345929632.dkr.ecr.eu-central-1.amazonaws.com/cloudmart-frontend
      tag: 4fe1ee40967379fa0562c19a7e854e8a54d010cc
    port: 80
    replicas: 2
    type: ClusterIP
    ingress:
      enabled: true
      path: /
      pathType: Prefix

  product-service:
    enabled: true
    image:
      repository: 500345929632.dkr.ecr.eu-central-1.amazonaws.com/cloudmart-product-service
      tag: 4fe1ee40967379fa0562c19a7e854e8a54d010cc
    port: 3000
    replicas: 2
    type: ClusterIP
    db:
      enabled: true
      storage: 1Gi

  user-service:
    enabled: true
    image:
      repository: 500345929632.dkr.ecr.eu-central-1.amazonaws.com/cloudmart-user-service
      tag: 4fe1ee40967379fa0562c19a7e854e8a54d010cc
    port: 3001
    replicas: 2
    type: ClusterIP
    db:
      enabled: true
      storage: 1Gi

  order-service:
    enabled: true
    image:
      repository: 500345929632.dkr.ecr.eu-central-1.amazonaws.com/cloudmart-order-service
      tag: 4fe1ee40967379fa0562c19a7e854e8a54d010cc
    port: 3002
    replicas: 2
    type: ClusterIP
    db:
      enabled: true
      storage: 1Gi
